### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by openhoat**
Allow vid/pid instead of path to instanciate HID

### CODE REVIEW

**Comment by watsoncj** [comment]
This appears to change the API in a way that's not backwards compatible.

For good measure the major version should get bumped and the rearms should be updated.

Alternatively, we could inspect the type of the first argument to maintain compatibility with the existing interface.

**Comment by watsoncj** [comment]
Typo above; I meant to say that the readme should be updated.

**Comment by emilyrose** [comment]
Hey @openhoat, @watsoncj 

Apologies for not noticing this sooner! I'm happy to discuss the best way to go about adding this functionality. ATM I'm partial to the idea of detecting argument type. What do you two think?

**Comment by watsoncj** [comment]
I like the idea of checking the type of opts and treating it as path if it's a string. 

I don't have any issues with breaking backwards compatibility though.

**Comment by openhoat** [comment]
Hi @emilyrose, @watsoncj 

Nice idea, simple and smart.

**Comment by emilyrose** [comment]
I totally forgot to ask this earlier, but could you add yourself to the package.json as a contributor? 😸

**Comment by emilyrose** [comment]
I will publish as v3.0 once we have everything dusted!

**Pull request merged**
